fix: Invites and Offline Player Commands being broken & update pom.xml
ToberoCat/ImprovedFactions pull request #202
Opened 2024-07-17 11:46 UTC by Specifix5

From what I've seen, getting player UUID from KnownOfflinePlayer.id.value directly does not identify the player UUID neither in online or offline mode. So invite commands fail as it will try to get an Unknown user.

I've also refactored some codes in invite discard command to accept the Factioninvite entity class provided by InviteIdArgument instead of an integer value, as it fails to cast.

Also updated plugin version in pom.xml to 2.2.1.

This PR fixes above mentioned issues as of 2.2.1-dev.

2024-07-17 11:48 UTC, Specifix5 commented
This fixes issue #201 and #182 as tested on Geyser

2024-07-17 12:07 UTC, Specifix5 commented
also fixed passive energy accumulation typo

2024-07-17 16:46 UTC, ToberoCat commented
Alright, the question was clarified based on the discord chat.
Just one minor change: For performance reasons I would prefer using the offline method as a fallback, because this can get pretty slow with a huge amount of players.

2024-07-17 16:52 UTC, ToberoCat requested changes
Overall good changes with some possible performance issue.

2024-07-17 16:52 UTC, ToberoCat commented on improved-factions-base/src/main/kotlin/io/github/toberocat/improvedfactions/utils/Extensions.kt
I'd suggest using this as fallback, because it's more performant using a database query. I'm case that one fails, using the Bukkit API is still a viable option.

2024-07-17 16:52 UTC, ToberoCat commented on improved-factions-base/src/main/resources/languages/messages_en.properties
You fixed the typo for passive (thank you), but did you update all commands, etc referring to this translation entry?

2024-07-17 23:05 UTC, Specifix5 commented on improved-factions-base/src/main/resources/languages/messages_en.properties
Yes, I updated all classes that references PowerChangeReason.PASSIV_ENERGY_ACCUMULATION.

2024-07-17 23:09 UTC, Specifix5 commented on improved-factions-base/src/main/kotlin/io/github/toberocat/improvedfactions/utils/Extensions.kt
For fake players. if you mean geyser, they still create a real player, if you go to the world/playerdata, bedrock UUIDs should start with 000 something.. (They also work with commands when a bedrock player is online) and for the fallback you requested, I'll try doing something about that when I get home, I just know that id.value doesnt return the correct UUID as of now.

2024-07-18 05:17 UTC, ToberoCat commented on improved-factions-base/src/main/resources/languages/messages_en.properties
Alright, just wanted to make sure.

2024-07-18 14:23 UTC, ToberoCat approved these changes
Everything seems fine

2024-07-18 14:28 UTC, merged